### DISCUSSION TITLE
How to change font family and font size ?

### DISCUSSION THREAD

**Discussion by inix** [PrismJS/prism#2859] [General]
The default font size seems more larger than other fonts.
How to change it?

**Comment by RunDevelopment** [comment]
By default, Prism's themes will use the [font size of the parent element](https://github.com/PrismJS/prism/blob/e0ee93f138b7da294a28db50b97c22977fdfc8ed/themes/prism.css#L13) and some monospace font that is specified by the theme ([example](https://github.com/PrismJS/prism/blob/e0ee93f138b7da294a28db50b97c22977fdfc8ed/themes/prism.css#L12)).

You can change the font family like this:

```css
code[class*="language-"],
pre[class*="language-"] {
  font-family: 'My cool font', monospace;
}
```

And the font size like this:


```css
code[class*="language-"],
pre[class*="language-"] {
  font-size: 12px;
}
```

However, when using a relative font size (e.g. `80%`, `0.8em`), it is important that you only apply it once! Prism uses `<pre><code>` elements for code blocks, so setting `font-size: 80%` on both of them will stack and cause the code to be displayed at only `64%` its original size.

Use this instead:

```css
:not(pre) > code[class*="language-"],
pre[class*="language-"] {
  font-size: 80%;
}
```

Hope this helps.
