### DISCUSSION TITLE
help with leading space

### DISCUSSION THREAD

**Discussion by IPvSean** [PrismJS/prism#3579] [Q&A]
I have a simple YAML block in prism...

```
---
- name: Apache server installed
  hosts: web
  become: true
  tasks:
```

but in this page->
https://www.ansible.com/overview/how-ansible-works#

It looks indented one space in...
![image](https://user-images.githubusercontent.com/6537680/196004113-0158caa4-1620-481e-a7f3-fa46a6e5d862.png)

I am confused.... on what I can do to fix that.  When I copy and paste it out of the text field its fine... the CSS looks identical for the line below, and I installed the normalizewhitespace plugin

anyone have a suggestion?
