### ISSUE TITLE
Word Wrapping

### ISSUE THREAD

**Issue by scratchyone** [PrismJS/prism#1247]
I'm using prism on my site, but the text is not wrapping. It has a really long scroll bar. How can I fix this? Here is the site: scratchyone.com/view-source/

**Comment by Golmote** [comment]
Hi! You can change the wrapping behaviour in Prism by simply overriding the `white-space` CSS property on `<pre>` and `<code>` tags.

**Comment by scratchyone** [comment]
Thanks! I'll do that the next time I use prism.

**Comment by ayoubkhan558** [comment]
Add this CSS in your code. It will fix the issue


```css
pre[class*="language-" ],
code[class*="language-"] {
    white-space: normal;
    overflow: auto;
    word-break: break-word;
}
```
