### ISSUE TITLE
Nothing special is rendered in <div> or <code> tags

### ISSUE THREAD

**Issue by ORESoftware** [PrismJS/prism#1260]
I have this in an Angular component:

```js
    this.muchoCodo = Prism.highlight(`

    import suman = require('suman');
    const {Test} = suman.init(module);

    Test.create((b, it, before) => {

      it('bahru', t => {

      });

    });

    `, Prism.languages.javascript);
```

and then in the HTML

```html
    <mat-card-content>
      ZOOM
      <div [innerHTML]="muchoCodo"></div>
    </mat-card-content>
```

it just renders this:
![screenshot 2018-01-06 11 47 18](https://user-images.githubusercontent.com/11139560/34643327-5ff18e12-f2d7-11e7-99b1-b2371a334d70.png)

if I don't set the innerHTML, then I get this:

`<span class="token keyword">import</span> suman <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'suman'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token keyword">const</span> <span class="token punctuation">{</span>Test<span class="token punctuation">}</span> <span class="token operator">=</span> suman<span class="token punctuation">.</span><span class="token function">init</span><span class="token punctuation">(</span>module<span class="token punctuation">)</span><span class="token punctuation">;</span> Test<span class="token punctuation">.</span><span class="token function">create</span><span class="token punctuation">(</span><span class="token punctuation">(</span>b<span class="token punctuation">,</span> it<span class="token punctuation">,</span> before<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span> <span class="token function">it</span><span class="token punctuation">(</span><span class="token string">'bahru'</span><span class="token punctuation">,</span> t <span class="token operator">=></span> <span class="token punctuation">{</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>`

so perhaps I am just missing some CSS? what to do?

**Comment by ORESoftware** [comment]
I also tried this:

```html
    <mat-card-content>
      ZOOM
      <div class="language-js" [innerHTML]="muchoCodo"></div>
    </mat-card-content>
```

I added a class to the div, but that didn't change anything

**Comment by ORESoftware** [comment]
So I get this error when loading this CSS:

![screenshot 2018-01-06 12 12 15](https://user-images.githubusercontent.com/11139560/34643555-df282134-f2da-11e7-8d72-88cc802edc82.png)


```css
/* PrismJS 1.9.0
http://prismjs.com/download.html?themes=prism-solarizedlight&languages=markup+css+clike+javascript */
/*
 Solarized Color Schemes originally by Ethan Schoonover
 http://ethanschoonover.com/solarized

 Ported for PrismJS by Hector Matos
 Website: https://krakendev.io
 Twitter Handle: https://twitter.com/allonsykraken)
*/

/*
SOLARIZED HEX
--------- -------
base03    #002b36
base02    #073642
base01    #586e75
base00    #657b83
base0     #839496
base1     #93a1a1
base2     #eee8d5
base3     #fdf6e3
yellow    #b58900
orange    #cb4b16
red       #dc322f
magenta   #d33682
violet    #6c71c4
blue      #268bd2
cyan      #2aa198
green     #859900
*/

code[class*="language-"],
pre[class*="language-"] {
	color: #657b83; /* base00 */
	font-family: Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace;
	text-align: left;
	white-space: pre;
	word-spacing: normal;
	word-break: normal;
	word-wrap: normal;

	line-height: 1.5;

	-moz-tab-size: 4;
	-o-tab-size: 4;
	tab-size: 4;

	-webkit-hyphens: none;
	-moz-hyphens: none;
	-ms-hyphens: none;
	hyphens: none;
}

pre[class*="language-"]::-moz-selection, pre[class*="language-"] ::-moz-selection,
code[class*="language-"]::-moz-selection, code[class*="language-"] ::-moz-selection {
	background: #073642; /* base02 */
}

pre[class*="language-"]::selection, pre[class*="language-"] ::selection,
code[class*="language-"]::selection, code[class*="language-"] ::selection {
	background: #073642; /* base02 */
}

/* Code blocks */
pre[class*="language-"] {
	padding: 1em;
	margin: .5em 0;
	overflow: auto;
	border-radius: 0.3em;
}

:not(pre) > code[class*="language-"],
pre[class*="language-"] {
	background-color: #fdf6e3; /* base3 */
}

/* Inline code */
:not(pre) > code[class*="language-"] {
	padding: .1em;
	border-radius: .3em;
}

.token.comment,
.token.prolog,
.token.doctype,
.token.cdata {
	color: #93a1a1; /* base1 */
}

.token.punctuation {
	color: #586e75; /* base01 */
}

.namespace {
	opacity: .7;
}

.token.property,
.token.tag,
.token.boolean,
.token.number,
.token.constant,
.token.symbol,
.token.deleted {
	color: #268bd2; /* blue */
}

.token.selector,
.token.attr-name,
.token.string,
.token.char,
.token.builtin,
.token.url,
.token.inserted {
	color: #2aa198; /* cyan */
}

.token.entity {
	color: #657b83; /* base00 */
	background: #eee8d5; /* base2 */
}

.token.atrule,
.token.attr-value,
.token.keyword {
	color: #859900; /* green */
}

.token.function {
	color: #b58900; /* yellow */
}

.token.regex,
.token.important,
.token.variable {
	color: #cb4b16; /* orange */
}

.token.important,
.token.bold {
	font-weight: bold;
}
.token.italic {
	font-style: italic;
}

.token.entity {
	cursor: help;
}
```
