### ISSUE TITLE
Prism showing white lines between rules 

### ISSUE THREAD

**Issue by Hapeki** [PrismJS/prism#1373]
I have prismjs installed on my ghost server.  There are white lines visible between my rules:

<img width="250" alt="screen shot 2018-03-29 at 21 47 20" src="https://user-images.githubusercontent.com/28729992/38110195-1ccf6348-339b-11e8-96ca-354f00726470.png">

The programming language is Swift. I get these results on Chrome and Safari (All I tested).

**Comment by Golmote** [comment]
Hi! Can you provide on online example reproducing this issue please?

**Comment by Hapeki** [comment]
@Golmote sure you can find the example on my website: https://hapeki.com/protocol-oriented-programming/

**Comment by Golmote** [comment]
@Hapeki You do have a CSS rule that adds an inset `box-shadow` on your `<code>` elements.

Cf https://hapeki.com/assets/css/style.css?v=cfb97db1c3 at lines 195-196.

```css
code, tt {
    ...
    -webkit-box-shadow:inset 0 0 1px 0 #e6e6e6;
    box-shadow:inset 0 0 1px 0 #e6e6e6;
}
```
