### ISSUE TITLE
Class name highlighting for Eiffel

### ISSUE THREAD

**Issue by finnianr** [PrismJS/prism#1383]
The most popular Eiffel IDE (EiffelStudio) highlights Eiffel class names with the color blue. [Screenshot](https://www.eiffel.com/wp-content/uploads/images/screenshots/built_in_design_by_contract.png) If PrismJS could do the same I think it would be much appreciated by the Eiffel community. This should be relatively easy to achieve as any identifier consisting of all upper case letters can be assumed to be a class name. This is a universal naming convention in the Eiffel community.

**Comment by Golmote** [comment]
So I just tested it, and it appears the uppercased class names in Eiffel are already matched and highlighted.
The color of the token essentially depends of the theme, so there is nothing we can really do here. If you want to change the color of those tokens in your specific CSS, you can always add a rule for it:

```css
.language-eiffel .token.class-name {
    color: blue; /* or whatever shade of blue you want */
}
```
