### ISSUE TITLE
CSS - Text selection color is global?

### ISSUE THREAD

**Issue by dewyatt** [PrismJS/prism#170]
In the CSS I see this:

``` css
/* Text Selection colour */
::selection {
    background: hsla(0,0%,93%,0.15); /* #EDEDED */
}
```

This sets the text selection for the entire document.
Is this a bug workaround or something?
I think something more specific should be used here.

I'm not skilled at CSS but I found something like this works for code and leaves the rest of the page alone:

``` css
/* Text Selection colour */
code[class*="language-"]::selection,
code[class*="language-"] span::selection {
    background: hsla(0,0%,93%,0.15); /* #EDEDED */
}
```
