### ISSUE TITLE
"Line Numbers" plugin removes all indentation from my code.

### ISSUE THREAD

**Issue by steven7mwesigwa** [PrismJS/prism#1963]
**Information:**
- Prism version: [1.16.0]
- Environment: [e.g. Browser]

Does the latest version of Prism from the [download page](https://prismjs.com/download.html) also have this issue? YES.

**Description**
*a.* Here is code on my blog https://gist.github.com/steven7mwesigwa/3b191cbeafcb3f9d0260aeeaaf828da7
*b.* When i download the [JS](https://gist.github.com/steven7mwesigwa/fe0c642ba101b45527ebbdfacb7b2c48) and [CSS](https://gist.github.com/steven7mwesigwa/38a06a1e8165f3990ae83778f10eb193) prism files **without** _line numbers plugin_, the code remains indented as it was before.
*c.* Once i repeat step **b.** for [JS](https://gist.github.com/steven7mwesigwa/9a875ba2ecc2412ca4b24e657ea5ee4f) and [CSS](https://gist.github.com/steven7mwesigwa/0274fb56bb1dd91b9189d86a7310564d) prism files *BUT* **_with_** _line numbers plugin_, the code looses all it's indentation.
*d.* I checked the two CSS prism files to see the difference between the two, and realised the code below as the difference.
```css
pre[class*="language-"].line-numbers {
	position: relative;
	padding-left: 3.8em;
	counter-reset: linenumber;
}

pre[class*="language-"].line-numbers > code {
	position: relative;
	white-space: inherit;
}

.line-numbers .line-numbers-rows {
	position: absolute;
	pointer-events: none;
	top: 0;
	font-size: 100%;
	left: -3.8em;
	width: 3em; /* works for line-numbers below 1000 lines */
	letter-spacing: -1px;
	border-right: 1px solid #999;

	-webkit-user-select: none;
	-moz-user-select: none;
	-ms-user-select: none;
	user-select: none;

}

	.line-numbers-rows > span {
		pointer-events: none;
		display: block;
		counter-increment: linenumber;
	}

		.line-numbers-rows > span:before {
			content: counter(linenumber);
			color: #999;
			display: block;
			padding-right: 0.8em;
			text-align: right;
		}
```
*d.* Unfortunately amnot conversant enough to modify the above code to ***disable*** the _removal_ of the original indentation.

I want to add **line numbers** BUT loosing indentation is just too bad for me. Please help...
