### ISSUE TITLE
No longer compatible with MkDocs static-site generator

### ISSUE THREAD

**Issue by kxcontrib** [PrismJS/prism#2099]
The [MkDocs static-site generator](https://mkdocs.org/) has a code-highlighting plugin based on Pygments. We use Prism instead, because it supports the q (kdb+database) language. 

[code.kx.com](https://code.kx.com/)

Trying to upgrade Prism, I cannot find a current JS that works. With my 2017 JS everything works. Switch in a current JS or link to the CDN and highlighting disappears. No warning or error in the browser console. Problem is reproducible from the minimal MkDocs instance created by `mkdocs new` command with inclusion of folders `docs/scripts` and `docs/stylesheets`. (Attached.) Configuration file:

```yaml
#  MkDocs sandbox for testing features
extra_css:
  # - stylesheets/prism.css
  - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/themes/prism-solarizedlight.min.css'
extra_javascript:
  - 'https://code.jquery.com/jquery-3.4.1.min.js'
  - scripts/prism0.js
  # - scripts/prism.js
  # - 'https://cdnjs.cloudflare.com/ajax/libs/prism/1.17.1/prism.min.js'
site_name: Sandbox
```
Above, `prism.js` is the minimal file downloaded currently from prismjs.com, and `prism0.js` is the corresponding file from August 2017. 

We value the code highlighting Prism gives us and want to stay current. 

Attached is a ZIP of the entire MkDocs instance.

[archive.zip](https://github.com/PrismJS/prism/files/3748143/archive.zip)
