### ISSUE TITLE
Support markdown front matter

### ISSUE THREAD

**Issue by RunDevelopment** [PrismJS/prism#2115]
**Motivation**
When highlighting GitHub's issue or PR templates or markdown files for Jekyll, the meta info about those files isn't highlighted.

**Description**
Front matter is a short section of meta-information in YAML (or similar languages) about a file and usually looks like this:

```yml
---
layout: post
title: Blogging Like a Hacker
---
```

For now, it should be enough to support YAML front matter as that seems to be the most common.
