### ISSUE TITLE
Code comments not visible on Mobile Safari

### ISSUE THREAD

**Issue by timroesner** [PrismJS/prism#2314]
**Information:**
- Prism version: 1.20
- Plugins: none
- Environment: Browser

**Description**
Code comments are not visible on Mobile Safari (iPhone, iPod, iPad). Reason for that is that these clients define the following in their User Agent Style Sheet:
```css
.comment {
   display: none;
}
```

Which is in conflict with the way Prism defines the span for code comments:
```html
<span class="token comment">// ...</span>
```

**Example**
See above

**Comment by RunDevelopment** [comment]
To fix this we could add this to all themes:

```css
span.token {
    display: inline;
}
```

Can somebody please reproduce the issue? I don't own any Apple devices.

---

@timroesner 
You might want to open an issue in [`normalize.css`](https://github.com/necolas/normalize.css).

**Comment by timroesner** [comment]
I tried adding this to my index.css:
```css
.comment {
    display: inline ! important;
}
```

I do see it overwriting the User Agent Style Sheet, but for whatever reason Safari on iOS still hides the code comment. 
Only work around I have found was renaming the span class to something other than `comment` , but unfortunately that name is chosen by prism so I can only do that in the web inspector.
