### ISSUE TITLE
SCSS functions not correctly marked

### ISSUE THREAD

**Issue by jaydenseric** [PrismJS/prism#237]
SCSS functions are not marked at all.

In this example, `myfunction` should be marked with the classnames `token function` like when highlighting functions in JS.

``` scss
::before {
    content: myfunction($variable);
}
```
