### ISSUE TITLE
How to style line numbers?

### ISSUE THREAD

**Issue by djmtype** [PrismJS/prism#2741]
I figured out how to style the actual line numbers: 

```css
pre[class*="language-"].line-numbers span::before
 {
  color: var(--my color);
}
```

HOWEVER… 
Using web inspector, I can't see where to style the vertical border between the line numbers and the code snippet. 
How do we style this?

**Comment by djmtype** [comment]
Nevermind, I think it's this: 

```css
pre[class*="language-"].line-numbers:before {
	border-color: #00f;
}
```
