### ISSUE TITLE
YAML works on Github pages but not Hubspot?

### ISSUE THREAD

**Issue by IPvSean** [PrismJS/prism#3378]
**Information**
- Language: YAML
- Plugins: none

tried multiple versions of prism... I am struggling here b/c I have the exact same setup on my exercises working fine with YAML

**Description**
On the blog I wrote here: https://www.ansible.com/blog/how-to-migrate-your-ansible-playbooks-to-support-aws-boto3

It does not work...
![image](https://user-images.githubusercontent.com/6537680/157597341-4f7c3d39-a52d-48f0-90ff-41f77e412716.png)

On an exercise I wrote, with exact same CSS and JavaScript... it does work:
https://aap2.demoredhat.com/exercises/ansible_network/2-first-playbook/
<img width="531" alt="image" src="https://user-images.githubusercontent.com/6537680/157597363-16edc418-78de-4b0e-95ac-2844c425a187.png">

**Code snippet**

```
<p>Let's look at an older version of a task file from our technical workshops so I can show you how to convert from ec2 to <a href="https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_instance_module.html#ansible-collections-amazon-aws-ec2-instance-module"><span>ec2_instance</span></a>:</p>
<!-- {% raw %} -->
<pre><code class="language-yml">---
- name: Create EC2 instances for RHEL8
  ec2:
    assign_public_ip: true
    key_name: "{{ ec2_name_prefix }}-key"
    group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_info[rhel8].size }}"
    image: "{{ node_ami_rhel.image_id }}"
    region: "{{ ec2_region }}"
    exact_count: "{{ student_total }}"
    count_tag:
      Workshop_node1": "{{ ec2_name_prefix }}-node1"
    instance_tags:
      Workshop_node1": "{{ ec2_name_prefix }}-node1"
      Workshop: "{{ ec2_name_prefix }}"
      Workshop_type: "{{ workshop_type }}"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ ec2_info[control_type].disk_space }}"
        delete_on_termination: true
  register: control_output
</code></pre>
<!-- {% endraw %} -->
<p>For booting an instance into AWS, there are only six required parameters. You need to specify a key (i.e. the SSH key to access the image), security group (virtual firewall for your ec2 instances), instance_type (e.g. t2.medium), a region (i.e. us-east-1), image (e.g. an AMI for RHEL8) and a network interface or VPC subnet id (vpc_subnet_id).&nbsp;</p>
<p>The rest of the parameters in my task above are for:</p>
```

(i have tired with and without the raw tags....)

ALSO CSS will work on the blog... only YAML doesn't work?  I am doing something silly/wrong

[Test page](https://prismjs.com/test.html#language=yaml&text=---%0A-%20name%3A%20Create%20EC2%20instances%20for%20RHEL8%0A%20%20ec2%3A%0A%20%20%20%20assign_public_ip%3A%20true%0A%20%20%20%20key_name%3A%20%22%7B%7B%20ec2_name_prefix%20%7D%7D-key%22%0A%20%20%20%20group%3A%20%22%7B%7B%20ec2_security_group%20%7D%7D%22%0A%20%20%20%20instance_type%3A%20%22%7B%7B%20ec2_info%5Brhel8%5D.size%20%7D%7D%22%0A%20%20%20%20image%3A%20%22%7B%7B%20node_ami_rhel.image_id%20%7D%7D%22%0A%20%20%20%20region%3A%20%22%7B%7B%20ec2_region%20%7D%7D%22%0A%20%20%20%20exact_count%3A%20%22%7B%7B%20student_total%20%7D%7D%22%0A%20%20%20%20count_tag%3A%0A%20%20%20%20%20%20Workshop_node1%22%3A%20%22%7B%7B%20ec2_name_prefix%20%7D%7D-node1%22%0A%20%20%20%20instance_tags%3A%0A%20%20%20%20%20%20Workshop_node1%22%3A%20%22%7B%7B%20ec2_name_prefix%20%7D%7D-node1%22%0A%20%20%20%20%20%20Workshop%3A%20%22%7B%7B%20ec2_name_prefix%20%7D%7D%22%0A%20%20%20%20%20%20Workshop_type%3A%20%22%7B%7B%20workshop_type%20%7D%7D%22%0A%20%20%20%20wait%3A%20%22%7B%7B%20ec2_wait%20%7D%7D%22%0A%20%20%20%20vpc_subnet_id%3A%20%22%7B%7B%20ec2_vpc_subnet_id%20%7D%7D%22%0A%20%20%20%20volumes%3A%0A%20%20%20%20%20%20-%20device_name%3A%20%2Fdev%2Fsda1%0A%20%20%20%20%20%20%20%20volume_type%3A%20gp2%0A%20%20%20%20%20%20%20%20volume_size%3A%20%22%7B%7B%20ec2_info%5Bcontrol_type%5D.disk_space%20%7D%7D%22%0A%20%20%20%20%20%20%20%20delete_on_termination%3A%20true%0A%20%20register%3A%20control_outpu)

<details>
<summary>The code is not being highlighted at all for YAML.</summary>

```
<pre><code class="language-yml">---
- name: Create EC2 instances for RHEL8
  ec2:
    assign_public_ip: true
    key_name: "{{ ec2_name_prefix }}-key"
    group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_info[rhel8].size }}"
    image: "{{ node_ami_rhel.image_id }}"
    region: "{{ ec2_region }}"
    exact_count: "{{ student_total }}"
    count_tag:
      Workshop_node1": "{{ ec2_name_prefix }}-node1"
    instance_tags:
      Workshop_node1": "{{ ec2_name_prefix }}-node1"
      Workshop: "{{ ec2_name_prefix }}"
      Workshop_type: "{{ workshop_type }}"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ ec2_info[control_type].disk_space }}"
        delete_on_termination: true
  register: control_output
```

</details>
