### ISSUE TITLE
URI language plugin not highlighting

### ISSUE THREAD

**Issue by Niek** [PrismJS/prism#3439]
**Information:**
- Prism version: 1.28.0
- Plugins: autoloader
- Environment: browser

**Description**
The URI language doesn't seem to work in at least v1.28.0. I can't get it to highlight any URI, no matter what I try (various themes etc). The URI component is loaded correctly, I just don't see any highlighting.

**Example**
See sample here: https://codepen.io/NiekvdMaas/pen/jOYJYWj

**Comment by RunDevelopment** [comment]
> I just don't see any highlighting.

That's intentional. URI is supposed to be a language that other languages can embed. E.g. HTTP uses URI to tokenize its URLs. URI doesn't use tokens that our themes highlight because that highlighting wouldn't look good when embedded in other languages. 

Our themes currently don't support more subtle highlighting for embedded, so we leave it up to the user to modify their theme to give URIs highlighting.

**Comment by Niek** [comment]
Thanks for the reply, that makes sense now. I see it can be styled easily with a custom stylesheet. In case anyone is interested, this is a colour scheme that works for me (using the `tomorrow` theme):
```css
.token.scheme {
    color: #cc99cd;
}

.token.host,
.token.port {
    color: #f08d49;
}

.token.key {
    color: #ccc;
}

.token.value {
    color: #7ec699;
}

.token.query-delimiter,
.token.pair-delimiter,
.token.authority-delimiter,
.token.path-separator,
.token.port-delimiter,
.token.pair {
    color: #67cdcc;
}
```
