### ISSUE TITLE
CSS selectors with inline comments are not tokenised/highlighted correctly

### ISSUE THREAD

**Issue by querkmachine** [PrismJS/prism#3676]
**Information:**
- Prism version: 1.29.0
- Plugins: none
- Environment: Browser, Node

**Description**
Sometimes when writing documentation, I will place short comments inside or alongside complex CSS selectors, so that I can write a comment explaining the parts of the selector elsewhere in the file. 

However, PrismJS seems to 'split' the selector on these comments, and will only tokenise and highlight the final part of the selector. This is unexpected as the CSS is valid. 

Perhaps this should be added to the [known failures](https://prismjs.com/known-failures.html) in the interim? 

**Example**

A sample of the code I'm using:

```css
/**
 * Supported CAPTCHAs:
 * (1) Google reCAPTCHA
 * (2) hCaptcha
 * (3) Cloudflare Turnstile
 * (4) Microsoft CAPTCHA
 */

/* 1 */ #recaptcha-anchor-label,
/* 2 */ body > div#anchor > div.label-container > label-td > label-tc > div#label,
/* 3 */ #cf-stage #challenge-stage .ctp-label,
/* 4 */ #root > .box > .box > p[data-theme="home.instructions"] {
  font-size: 0 !important;
  line-height: 0 !important;
}
```

How it renders on the [test drive page](https://prismjs.com/test.html#language=css):

<img width="916" alt="image" src="https://user-images.githubusercontent.com/1253214/235189146-1f23f51f-c8f3-49ed-b25d-8e17a0f37507.png">
