### ISSUE TITLE
Plugin line-highlight always has a padding-left of 3em when data-line=""

### ISSUE THREAD

**Issue by zxyao145** [PrismJS/prism#3749]
**Information:**
- Prism version:  1.29.0
- Plugins: line-highlight
- Environment: Browser

**Description**
if `data-line=""`, the padding-left always is 3em.

![image](https://github.com/PrismJS/prism/assets/24973084/590066d5-f6d6-4af7-8e84-dd9c5194b2cb)

The relevant CSS is as follows:

https://github.com/PrismJS/prism/blob/59e5a3471377057de1f401ba38337aca27b80e03/plugins/line-highlight/prism-line-highlight.css#L1-L4

Perhaps it would be better to modify it to the following format?

```css
pre[data-line]:not([data-line=""]) {
	position: relative;
	padding: 1em 0 1em 3em;
}
```
