### ISSUE TITLE
Scrollbars are always enabled, even in single-line pieces of code

### ISSUE THREAD

**Issue by FinestRocker** [PrismJS/prism#559]
I downloaded prism and did not touch any of the code. When I enable it in my Ghost blog, all of the code blocks have scroll bars. I've noticed that this does not happen to other Ghost blogs. The features I've enabled are "line numbers" and and "show language". You can see an example of what I mean in this blog post: http://antoniojsantos.me/assigning-values-to-variables/. All the other posts in my blog also have this issue. I am using the Casper theme with my own modifications (see the changes in my [fork](https://github.com/FinestRocker/Casper) of the theme). If you need any more information I'll gladly provide it.

**Comment by vkbansal** [comment]
The problem is in your `prism.css`

Find
```css
pre[class*='language-'] > code[data-language] {
  overflow: scroll;
  max-height: 28em;
  display: block;
}
```
and remove the `overflow:scroll` line
