### ISSUE TITLE
Namespace/prefix all the classes?

### ISSUE THREAD

**Issue by kizu** [PrismJS/prism#6]
As the Prism can be embedded in different environments, there could be already any of the class names that Prism uses, like `tag`, `token`, `number` etc. So it's possible that those styles would override or change Prism's.

The usual way to fix that is to use some prefix for all the classes used in Prism, so we can add the `prism-` prefix to all those classes: `prism-tag`, `prism-token`, `prism-number` etc.

I can't see any serious drawbacks, the gzip would cover neglect all the added prefixes.

**Comment by jonmilner** [comment]
@LeaVerou First of all, I think this project rocks. Thanks for all the work you've done to make it so simple for people like me to easily add syntax highlighting to our projects.

That being said, I'd like to offer the first "complaint" about a real collision on a real project that I'm working on.

I'm styling a UI component that my team has decided to call a "tag." Tags look like this:

<img width="210" alt="screen shot 2016-03-29 at 4 19 24 pm" src="https://cloud.githubusercontent.com/assets/937847/14122587/663557c4-f5ca-11e5-9326-b62385a07d5b.png">

Here's CSS I've written to style these tags:

```css
.tag {
  display: inline-block;
  max-width: 200px;
  margin-bottom: var(--base-spacing-xs);
  padding: var(--base-spacing-xs) var(--base-spacing-sm);
  border: 2px solid var(--base-accent-color);
  border-radius: 100px;
  color: var(--base-accent-color);
  font-size: var(--font-size-sm);
  font-weight: var(--font-weight-bold);
  line-height: 1;
  text-transform: uppercase;
  text-overflow: ellipsis;
  overflow: hidden;
  white-space: nowrap;
}
```

The problem here is that `<span class="token tag">...</span>` is inheriting the styles from our `.tag` component.

<img width="881" alt="screen shot 2016-03-29 at 4 29 39 pm" src="https://cloud.githubusercontent.com/assets/937847/14123276/c7996944-f5cd-11e5-8592-d9c280c185d1.png">

Obviously, when removed, the styles are fixed: 

<img width="880" alt="screen shot 2016-03-29 at 4 30 13 pm" src="https://cloud.githubusercontent.com/assets/937847/14123278/cac97f96-f5cd-11e5-83d1-d106ad46e4be.png">

I understand this may seem like an annoying request... If I had the domain knowledge, I'd be happy to submit a pull request on this issue.

Of course, I'm able to fix the issue myself if I were to prefix my own class names, or add the increased specificity by nesting my selectors, e.g...

<img width="879" alt="screen shot 2016-03-29 at 5 00 34 pm" src="https://cloud.githubusercontent.com/assets/937847/14124800/9055fe22-f5d5-11e5-8af5-0d69b3983c1c.png">

...but the way the classes are currently named in PrismJS prevents it from being used in combination with literally any other CSS library or custom CSS that include class names such as `.token`, `.tag`, `.punctuation`, `.number`, etc. at the root level.

The solution @kizu suggested seems pretty standard, and has no obvious drawbacks.
