### ISSUE TITLE
YAML Highlighting Incorrect w/Multiple Blocks

### ISSUE THREAD

**Issue by grayghostvisuals** [PrismJS/prism#649]
Currently YAML highlighting trips up when used in multiple blocks like so…

![screenshot 2015-07-28 16 01 57](https://cloud.githubusercontent.com/assets/934322/8942228/47eb1cd4-3542-11e5-9e75-4d57e74e3240.png)

This is correct YAML AFAIK or am I incorrect?

**Comment by nauzilus** [comment]
It looks like the leading `---` is important. It highlights correctly with that included.

I can't see to upload a screen shot, but you can probably test easily enough your self :smile: 

```
---
a:
  version: a
  modifierclass: active
  state: checked
b:
  version: b
  modifierclass: hidden
```
