### ISSUE TITLE
Apostrophe causing probelms for scss.liquid

### ISSUE THREAD

**Issue by suture** [PrismJS/prism#659]
Hi guys

in the .line-highlight class there is a comment that includes a curly apostrophe that looks like this ’
This causes problems on some systems such as Shopify, when it is trying to parse css in scss.liquid files. 
If you change it to a straight ' it works fine.

```css
.line-highlight {
	position: absolute;
	left: 0;
	right: 0;
	padding: inherit 0;
	margin-top: 1em;
	/* Same as .prism’s padding-top */
	background: rgba(153, 122, 102, 0.08);
	background: -moz-linear-gradient(left, rgba(153, 122, 102, 0.1) 70%, rgba(153, 122, 102, 0));
	background: -webkit-linear-gradient(left, rgba(153, 122, 102, 0.1) 70%, rgba(153, 122, 102, 0));
	background: -o-linear-gradient(left, rgba(153, 122, 102, 0.1) 70%, rgba(153, 122, 102, 0));
	background: linear-gradient(left, rgba(153, 122, 102, 0.1) 70%, rgba(153, 122, 102, 0));
	pointer-events: none;
	line-height: inherit;
	white-space: pre;
}
```
