### ISSUE TITLE
SCSS Class w/Pseudo Class Misparsed

### ISSUE THREAD

**Issue by Snugug** [PrismJS/prism#79]
I have the following using SCSS syntax highlighting:

``` scss
/*comment*/
.icon:before {
  font-family: 'Icon Font', sans-serif;
  content: 'icon';
}
```

The `.icon` is parsed into `.<span class="token property">icon</span>` producing incorrect highlighting for it.
