### ISSUE TITLE
How to disable shadows manually in coy theme.

### ISSUE THREAD

**Issue by garretwilson** [PrismJS/prism#894]
The coy theme comes with shadows. I would like to know how to turn them off manually from my own CSS.

Yes, I know that most of the time they look snazzy. Yes, I know that a lot of work has been put into them. Yes, I'm fine with them being turned on by default for screen media.

But for my purposes I just need to be able to disable them, even for screen. What is the easiest way for me to do this?

I've asked this question several times in Issue #859, but it must have got lost in the shuffle so I'm just filing a separate issue. Thanks.

**Comment by zeitgeist87** [comment]
Sorry if we missed your question. This should do it:

```css
pre[class*="language-"]:before,
pre[class*="language-"]:after {
    display: none;
}
```
