### ISSUE TITLE
Line highlight

### ISSUE THREAD

**Issue by reinos** [PrismJS/prism#930]
According #217 did you make any progress on this feature?

**Comment by vapits** [comment]
+1

My case is this:
http://stackoverflow.com/questions/36497869/is-it-possible-to-add-a-div-wrapper-in-prismjs-result

**Comment by Golmote** [comment]
Something like this?

```javascript
Prism.hooks.add('after-highlight', function (env) {
	env.element.innerHTML = '<div>' + env.highlightedCode.replace(/\r\n?|\n/g, '</div><div>') + '</div>';
});
```

You might want to add some CSS like so:

```css
code div:empty:before {
	content: '\00a0'; /* keeps empty divs visible */
}
```
